### PR TITLE
Fix TS errors

### LINKED ISSUE #1549: after upgrade from 0.8.2 to 0.9.1, receiving several errors all inside openapi-fetch
does 0.9.1 require any other updated deps?  

```
> shx rm -rf lib/ && tsc

node_modules/openapi-fetch/dist/index.d.ts:83:42 - error TS2314: Generic type 'FetchOptions' requires 1 type argument(s).

83 export type ParseAsResponse<T, O extends FetchOptions> = O extends {
                                            ~~~~~~~~~~~~

node_modules/openapi-fetch/dist/index.d.ts:119:40 - error TS2314: Generic type 'FetchOptions' requires 1 type argument(s).

119 export type FetchResponse<T, O extends FetchOptions> =
                                           ~~~~~~~~~~~~

node_modules/openapi-fetch/dist/index.d.ts:178:36 - error TS2344: Type 'M' does not satisfy the constraint 'HttpMethod'.

178   P extends PathsWithMethod<Paths, M>,
                                       ~

  node_modules/openapi-fetch/dist/index.d.ts:177:44
    177 export type ClientMethod<Paths extends {}, M> = <
                                                   ~
    This type parameter might need an `extends HttpMethod` constraint.

node_modules/openapi-fetch/dist/index.d.ts:179:31 - error TS2344: Type 'Paths[P]' does not satisfy the constraint '{}'.
  Type 'Paths[PathsWithMethod<Paths, M>]' is not assignable to type '{}'.
    Type 'Paths[Paths[keyof Paths] extends { [K in M]: any; } ? keyof Paths : never]' is not assignable to type '{}'.
      Type 'Paths[keyof Paths]' is not assignable to type '{}'.
        Type 'Paths[string] | Paths[number] | Paths[symbol]' is not assignable to type '{}'.
          Type 'Paths[string]' is not assignable to type '{}'.

179   I extends MaybeOptionalInit<Paths[P], M>,
                                  ~~~~~~~~

node_modules/openapi-fetch/dist/index.d.ts:183:28 - error TS2536: Type 'M' cannot be used to index type 'Paths[P]'.

183 ) => Promise<FetchResponse<Paths[P][M], I[0]>>;
```

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1549 by re-enabling `skipLibCheck: true`. Also updates some insignificant deps to make the fix easier.

The only significant changes are in `openapi-fetch`; all the other noise is from a type error from Vite/Vitest 🙃. There are probably other ways to have dealt with it, but this was the simplest. It seems to be [an upstream in issue in Rollup (maybe; who knows)](https://github.com/vitest-dev/vitest/issues/4567)

## How to Review

- The existing TS checks will fail now

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

**Comment by ericblade** [comment]
Cheers!

**Comment by hungify2022** [comment]
@drwpow 
After upgrading to 0.9.3
I have a new error when using this `MaybeOptionalInit<paths[P], 'get'>`

```
Type 'paths[P]' does not satisfy the constraint 'Record<HttpMethod, {}>'.
  Type '{ get: { parameters: { query?: { limit?: number | undefined; page?: number | undefined; id?: string | undefined; firstName?: string | undefined; lastName?: string | undefined; email?: string | undefined; phone?: string | undefined; } | undefined; };
```

I know that error but while `interface paths` looks like this
```
export interface paths {
  "/users": {
    /** get users with filter */
    get: operations["FindUsersHttpController_findUsers"];
    /** Create a user */
    post: operations["CreateUserHttpController_create"];
  };
}
```
'get'  | 'post' does not satisfy the HttpMethod
