### ISSUE TITLE
Property 'query' does not exist on type

### ISSUE THREAD

**Issue by nsb** [drwpow/openapi-typescript#995]
**Property 'query' does not exist on type**

In v5 I could get the type of query parameters from `operations['myOperationId']['parameters']['query']`, but this no longer works with v6. Instead I get type error `Property query does not exist on type { query?: { orderBy?: "id" | "created" | "name" | undefined; } | undefined; } | undefined`

```
type myQueryType = operations['myOperationId']['parameters']['query']

query' does not exist on type '{ query?: { orderBy?: "id" | "created" | "name" | undefined; } | undefined; } | undefined'
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.0.3`                      |
| Node.js              | `v18.9.1`                      |
| OS + version         | `Ubuntu 22.04` |

**Reproduction**

Generate types with v6.0.3 from YAML file that has a GET path with query parameters. Specific YAML file I used [https://github.com/nsb/myjobplanner-api/blob/286941f03ef8fc496c985cc4035922f3fd7d81f8/openapi.yaml](https://github.com/nsb/myjobplanner-api/blob/286941f03ef8fc496c985cc4035922f3fd7d81f8/openapi.yaml)

**Expected result**
I should be able to get the type definition of query parameters without type error

`type myQueryType = operations['myOperationId']['parameters']['query']`

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by niels-busch-maersk** [comment]
The issue is caused by `parameters` being possibly undefined. Is that a bug or problem with my schema?

**Comment by mkosir** [comment]
Can confirm the issue (when none of the parameters is required), it also happens for `requestBody` property.

**Comment by cdimitroulas** [comment]
+1, experiencing this issue on both `query` and `requestBody` properties which are now suddenly optional after upgrading to v6

**Comment by sgrimm** [comment]
This is happening at https://github.com/drwpow/openapi-typescript/blob/e91b1a85d2228d14063b10f16645699b7fa22a23/src/transform/operation-object.ts#L99 . Easy enough to remove the conditional there, but I'd want to know the reasoning behind the current behavior before submitting a PR to remove it.

**Comment by HunterKohler** [comment]
@sgrimm Do you think we can open a PR now? Its been quite a while and otherwise people need to use `NotNull` or similar to get around it.

**Comment by mkosir** [comment]
@drwpow any thoughts from your side would be highly appreciated on this issue?
Can PR be created as @sgrimm suggested, since this issues is quite blocking for many of us?

**Comment by nikeee** [comment]
We're also havong problems with this behaviour and it blocks us from upgrading to 6.x.

If changing the behaviour in is a problem, how about an extra flag to switch back to the old behaviour?

**Comment by mrclrchtr** [comment]
Ok, if anyone has the same problem... I managed it with @RequestBody(required = true):

```
  @Operation(summary = "Import")
  @PostMapping(
    "/import",
    consumes = [MediaType.MULTIPART_FORM_DATA_VALUE],
    produces = [MediaType.APPLICATION_JSON_VALUE],
  )
  fun import(
    @RequestBody(required = true)
    @RequestParam("file")
    file: MultipartFile,
  ) = ResponseEntity.ok()
```
